### ISSUE TITLE
Callbacks?

### ISSUE THREAD

**Issue by rpgoldman** [marcoheisig/cl4py#21]
Is it possible to call back into the Python interpreter?

I ask because if one passes a complex data structure into Lisp, it might be handy for Lisp to be able to ask Python to access it.

It seems like this is not possible at the moment, but perhaps I am wrong?

**Comment by marcoheisig** [comment]
This is not possible.  The design of cl4py is such that it mimics the synchronous communication with a REPL.  The only exception are complicated Lisp objects, which can be passed to Python as opaque handles.  If I'd allow the opposite, too, i.e., passing complicated Python objects to Lisp, we'd necessarily end up with data structures that mix Python and Lisp objects.  And such a data structure would be problematic, not just in terms of memory management, but because even just traversing such a structure could lead to hundreds of control transfers between Python and Lisp.

I should also state clearly that my main motivation for cl4py is to give Python programmers access to Lisp libraries, and not the other way around.

My practical suggestion would be to convert your complicated Python data structure into an s-expression made of cl4py.Cons cells, and to send that s-expression to Lisp.  This is one of the reasons why made sure that sending circular data is supported :)
